name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
      - 'feature-*'

jobs:
    unit-testing:
        name: Unit Testing
#        strategy:
#          matrix:
#            nodejs_version: [18, 19, 20]
#            operating_system: [ubuntu-latest, macos-latest]
#            exclude:
#              - nodejs_version: 18
#                operating_system: macos-lates
#
#        runs-on: ${{ matrix.operating_system }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          env:
            MONGO_URI: ${{ secrets.MONGO_DB_URI }}
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml